# Generated by Django 2.1.7 on 2019-06-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estruturaorganizacional',
            name='sucessora',
            field=models.ManyToManyField(blank=True, related_name='estruturas_sucessora_fk', to='core.EstruturaOrganizacional'),
        ),
    ]
