# Generated by Django 2.1.7 on 2019-06-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190618_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estruturaorganizacional',
            name='sucessora',
            field=models.ManyToManyField(blank=True, to='core.EstruturaOrganizacional'),
        ),
    ]
