# Generated by Django 2.1.7 on 2019-06-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190618_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroatividade',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição da Atividade'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='validacao_ch_por',
            field=models.CharField(choices=[('RESOLUCAO', 'Conforme resolução'), ('CURSO', 'Por Curso'), ('TURMA', 'Por turma'), ('DISCIPLINA', 'Por disciplina'), ('PROJETO', 'Por Projeto'), ('QUANTIDADE', 'Por quantidade informada no formulário')], default='RESOLUCAO', max_length=15, verbose_name='Validação da carga horária'),
        ),
    ]
