# Generated by Django 2.1.7 on 2019-06-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190624_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacaoargumento',
            name='valor_arquivo',
            field=models.FileField(blank=True, null=True, upload_to='arquivos/', verbose_name='Valor da informação Arquivo'),
        ),
        migrations.AlterField(
            model_name='argumentocategoria',
            name='tipo_dado',
            field=models.CharField(choices=[('TEXTO', 'Texto'), ('INTEIRO', 'Inteiro'), ('DECIMAL', 'Decimal'), ('BOOLEAN', 'Boolean'), ('DATA', 'Data'), ('HORA', 'Hora'), ('DATA_HORA', 'Data/Hora'), ('ARQUIVO', 'Arquivo')], max_length=20, verbose_name='Tipo de dado do campo'),
        ),
        migrations.AlterField(
            model_name='parametrosistema',
            name='tipo_dado',
            field=models.CharField(choices=[('TEXTO', 'Texto'), ('INTEIRO', 'Inteiro'), ('DECIMAL', 'Decimal'), ('BOOLEAN', 'Boolean'), ('DATA', 'Data'), ('HORA', 'Hora'), ('DATA_HORA', 'Data/Hora'), ('ARQUIVO', 'Arquivo')], max_length=20, verbose_name='Tipo de dado do parâmetro'),
        ),
    ]
