# Generated by Django 2.1.7 on 2019-06-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190626_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaatividade',
            name='is_importada',
            field=models.BooleanField(default=False, help_text='Indica que os         dados atividade será importado de um sistema externo.', verbose_name='Atividade importada?'),
        ),
    ]
