# Generated by Django 2.1.7 on 2019-07-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_categoriaatividade_is_importada'),
    ]

    operations = [
        migrations.AddField(
            model_name='estruturaorganizacional',
            name='sigla',
            field=models.CharField(blank=True, max_length=30, verbose_name='Sigla da estrutura organizacional'),
        ),
    ]
