# Generated by Django 2.1.7 on 2019-07-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_estruturaorganizacional_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='estruturaorganizacional',
            name='id_unidade_sig',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID da unidade nos SIGs'),
        ),
    ]
