# Generated by Django 2.1.7 on 2019-07-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_estruturaorganizacional_id_unidade_sig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estruturaorganizacional',
            name='id_unidade_sig',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID da unidade nos SIGs'),
        ),
    ]
