# Generated by Django 2.1.7 on 2019-07-31 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20190618_1108'),
        ('core', '0011_auto_20190731_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsavelUnidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_responsabilidade', models.CharField(choices=[('C', 'Chefia/Diretoria'), ('V', 'Vice-Chefia/Vice-Diretoria'), ('S', 'Secretaria'), ('A', 'Supervisor/Diretor Acadêmico')], max_length=5, verbose_name='Nível de responsabilidade')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_termino', models.DateField(blank=True, null=True, verbose_name='Data de termíno')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsaveis_unidade', to='authentication.ServidorProfile')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsaveis_unidade', to='core.EstruturaOrganizacional')),
            ],
            options={
                'verbose_name': 'Responsável da Unidade',
                'verbose_name_plural': 'Responsáveis da Unidade',
                'db_table': 'responsavel_unidade',
            },
        ),
    ]
