# Generated by Django 2.1.7 on 2019-07-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_responsavelunidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavelunidade',
            name='id_responsabilidade_sig',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID da responsabilidade nos SIGs'),
        ),
    ]
