# Generated by Django 2.1.7 on 2019-08-13 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20190801_1456'),
        ('core', '0015_auto_20190801_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='VinculoServidorUnidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portaria', models.CharField(max_length=150, verbose_name='Portaria')),
                ('tipo_vinculo', models.CharField(choices=[('P', 'Presidente'), ('V', 'Vice-Presidente'), ('S', 'Secretario'), ('M', 'Membro')], max_length=5, verbose_name='Tipo Vinculo')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_termino', models.DateField(blank=True, null=True, verbose_name='Data de termíno')),
                ('is_ativo', models.BooleanField(default=True, help_text='Indica que este vínculo será tratado como ativo. Ao invés de excluir o vínculo, desmarque isso.', verbose_name='Ativo?')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servidores_unidade', to='authentication.ServidorProfile')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servidores_unidade', to='core.EstruturaOrganizacional')),
            ],
            options={
                'verbose_name': 'Vínculo de Servidor com a Unidade',
                'verbose_name_plural': 'Vínculo de Servidores com as Unidades',
                'db_table': 'vinculo_servidor_unidade',
                'ordering': ['is_ativo', 'unidade'],
            },
        ),
        migrations.AlterModelOptions(
            name='responsavelunidade',
            options={'ordering': ('data_inicio', 'data_termino', 'unidade'), 'verbose_name': 'Responsável da Unidade', 'verbose_name_plural': 'Responsáveis da Unidade'},
        ),
    ]
