# Generated by Django 2.1.7 on 2019-08-13 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20190801_1456'),
        ('core', '0016_auto_20190813_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaTramite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_assinatura', models.DateTimeField(auto_now_add=True)),
                ('is_autenticador', models.BooleanField(default=False, verbose_name='Autenticador?')),
                ('servidor_assinante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servidor_assinante_fk', to='authentication.ServidorProfile')),
            ],
            options={
                'verbose_name': 'Assinatura do trâmite',
                'verbose_name_plural': 'Assinaturas dos trâmites',
                'db_table': 'assinatura_tramite',
                'ordering': ['tramite', 'data_assinatura'],
            },
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='Data de envio do processo')),
                ('despacho', models.TextField(blank=True, null=True, verbose_name='Despacho')),
                ('data_despacho', models.DateTimeField(blank=True, null=True, verbose_name='Data do despacho')),
                ('data_recebimento', models.DateTimeField(blank=True, null=True, verbose_name='Data do recebimento do processo')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processo_tramitado', to='core.Processo')),
                ('servidor_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servidor_destino_fk', to='authentication.ServidorProfile')),
                ('servidor_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servidor_origem_fk', to='authentication.ServidorProfile')),
                ('servidor_recebimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servidor_recebimento_fk', to='authentication.ServidorProfile')),
                ('unidade_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidade_destino_fk', to='core.EstruturaOrganizacional')),
                ('unidade_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidade_origem_fk', to='core.EstruturaOrganizacional')),
            ],
            options={
                'verbose_name': 'Tramitação de processo',
                'verbose_name_plural': 'Tramitação de processos',
                'db_table': 'tramite',
                'ordering': ['processo', 'data_criacao', 'data_envio'],
            },
        ),
        migrations.AddField(
            model_name='assinaturatramite',
            name='tramite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinatura_tramite', to='core.Tramite'),
        ),
    ]
