# Generated by Django 2.1.7 on 2019-08-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190815_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaatividade',
            name='is_restricao_chsemanal',
            field=models.BooleanField(default=False, help_text='Indica se         esta categoria possui parâmetro de carga horária semanal mínima e/ou máxima.', verbose_name='Existe restrição de carga horária?'),
        ),
    ]
