# Generated by Django 2.1.7 on 2019-08-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_fluxoprocesso_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaatividade',
            name='is_restricao_ch_semanal',
            field=models.BooleanField(default=False, help_text='Indica que os         dados atividade tem restrição de carga horária semanal.', verbose_name='Atividade tem restrição de carga horária semanal?'),
        ),
    ]
