# Generated by Django 2.1.7 on 2019-08-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_categoriaatividade_is_restricao_chsemanal'),
        ('core', '0020_categoriaatividade_is_restricao_ch_semanal'),
    ]

    operations = [
    ]
