# Generated by Django 2.1.7 on 2019-08-16 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_merge_20190816_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriaatividade',
            name='is_restricao_chsemanal',
        ),
    ]
