# Generated by Django 2.1.7 on 2019-08-19 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_categoriaatividade_is_restricao_chsemanal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='processo_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos_pai', to='core.Processo'),
        ),
    ]
