# Generated by Django 2.1.7 on 2019-08-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20190819_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadefluxoprocesso',
            name='is_avaliadora',
            field=models.BooleanField(default=False, help_text='Indica que os         membros da unidade poderão avaliar as atividades informadas no PIT/RIT.', verbose_name='Unidade Avaliadora?'),
        ),
    ]
