# Generated by Django 2.1.7 on 2019-08-20 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20190819_1039'),
        ('core', '0025_auto_20190819_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroatividade',
            name='avaliador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registro_atividades', to='authentication.ServidorProfile'),
        ),
        migrations.AddField(
            model_name='registroatividade',
            name='data_avaliacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da avaliacao'),
        ),
        migrations.AddField(
            model_name='registroatividade',
            name='is_validada',
            field=models.NullBooleanField(help_text='Indica que a         atividade está válida. Para informar que a atividade está inválida, desmarque isso.', verbose_name='Atividade válida?'),
        ),
        migrations.AddField(
            model_name='registroatividade',
            name='justificativa',
            field=models.TextField(blank=True, verbose_name='Justificativa atividade inválida'),
        ),
    ]
