# Generated by Django 2.2.4 on 2019-08-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20190820_1506'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='unidadefluxoprocesso',
            constraint=models.UniqueConstraint(condition=models.Q(is_ativo=True), fields=('unidade', 'fluxo_processo'), name='unique_active_unidade'),
        ),
    ]
