# Generated by Django 2.2.4 on 2019-08-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20190821_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroatividade',
            name='is_validada',
        ),
        migrations.AddField(
            model_name='registroatividade',
            name='situacao',
            field=models.CharField(choices=[('AGUARDANDO_VALIDACAO', 'Aguardando validação'), ('VALIDA', 'Válida'), ('INVALIDA', 'Inválida'), ('EDITADA', 'Editada')], default='AGUARDANDO_VALIDACAO', max_length=30, verbose_name='Situação atividade'),
        ),
        migrations.AlterField(
            model_name='registroatividade',
            name='justificativa',
            field=models.TextField(blank=True, help_text='Caso a atividade seja inválida justifique', verbose_name='Justificativa atividade inválida'),
        ),
    ]
