# Generated by Django 2.2.4 on 2019-08-28 15:16

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0031_tramite_is_rascunho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramite',
            name='is_rascunho',
        ),
        migrations.CreateModel(
            name='DocumentoProcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacao_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(blank=True, max_length=255, verbose_name='Assunto')),
                ('tipo_documento', models.CharField(choices=[('PARECER', 'Parecer')], default='PARECER', max_length=10, verbose_name='Tipo do documento')),
                ('texto', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Despacho')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Arquivo')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentoprocesso_requests_created', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentoprocesso_requests_modified', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_processo', to='core.Processo')),
            ],
            options={
                'verbose_name': 'Documento do processo',
                'verbose_name_plural': 'Documentos dos processos',
                'db_table': 'documento_processo',
            },
        ),
    ]
