# Generated by Django 2.2.4 on 2019-08-28 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20190819_1039'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0032_auto_20190828_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_assinatura', models.DateTimeField(auto_now_add=True)),
                ('is_autenticador', models.BooleanField(default=False, verbose_name='Autenticador?')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
                ('servidor_assinante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servidor_assinante_fk', to='authentication.ServidorProfile')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'db_table': 'assinatura',
                'ordering': ['data_assinatura'],
            },
        ),
        migrations.DeleteModel(
            name='AssinaturaTramite',
        ),
    ]
