# Generated by Django 2.2.4 on 2019-09-03 20:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20190828_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaprocesso',
            name='categoria_atividade',
            field=models.ManyToManyField(blank=True, null=True, related_name='categoria_processo_atividade_fk', to='core.CategoriaAtividade'),
        ),
        migrations.AlterField(
            model_name='documentoprocesso',
            name='texto',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='documentoprocesso',
            name='tipo_documento',
            field=models.CharField(choices=[('PARECER', 'Parecer'), ('DESPACHO', 'Despacho')], default='PARECER', max_length=10, verbose_name='Tipo do documento'),
        ),
        migrations.AlterField(
            model_name='documentoprocesso',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Título'),
        ),
    ]
