# Generated by Django 2.2.4 on 2019-09-04 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20190904_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='unidade_interessada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processos_unidade_interessada', to='core.EstruturaOrganizacional'),
        ),
    ]
