# Generated by Django 2.1.7 on 2019-06-18 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscenteProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Matrícula')),
                ('id_discente_sig', models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID do discente nos SIGAA')),
                ('is_ativo', models.BooleanField(default=True, help_text='Indica que o perfil será tratado como ativo. Ao invés de excluir perfis, desmarque isso.', verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Discente',
                'verbose_name_plural': 'Discentes',
            },
        ),
        migrations.CreateModel(
            name='GrupoDocente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('is_ativo', models.BooleanField(default=True, help_text='Indica que o grupo será tratado como ativo. Ao invés de excluir grupos, desmarque isso.', verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Grupo do docente',
                'verbose_name_plural': 'Grupos dos docentes',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('nome_mae', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome da mãe')),
                ('nome_pai', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do pai')),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], default='F', max_length=2, verbose_name='Sexo')),
                ('registro_geral', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número do Registro Geral')),
                ('rg_orgao_expedidor', models.CharField(blank=True, max_length=10, null=True, verbose_name='Órgão expedidor do RG')),
                ('rg_data_expedicao', models.DateField(blank=True, null=True, verbose_name='Data de expedição do RG')),
                ('rg_uf', models.IntegerField(blank=True, choices=[(1, 'AL'), (2, 'AM'), (3, 'AP'), (4, 'BA'), (5, 'CE'), (6, 'DF'), (7, 'ES'), (8, 'GO'), (9, 'MA'), (10, 'MG'), (11, 'MS'), (12, 'MT'), (13, 'PA'), (14, 'PE'), (15, 'PI'), (16, 'PR'), (17, 'RO'), (18, 'RN'), (19, 'RR'), (20, 'SC'), (21, 'SE'), (22, 'SP'), (23, 'TO'), (24, 'PB'), (25, 'RS'), (26, 'AC'), (27, 'RJ'), (99, 'ND'), (-1, 'I')], null=True, verbose_name='UF do RG')),
                ('grupo_sanguineo', models.IntegerField(blank=True, choices=[(1, 'A+'), (2, 'A-'), (3, 'B+'), (4, 'B-'), (5, 'AB+'), (6, 'AB-'), (7, 'O+'), (8, 'O-')], null=True, verbose_name='Grupo sanguíneo')),
                ('id_pessoa_sig', models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID da pessoa nos SIGs')),
            ],
        ),
        migrations.CreateModel(
            name='ServidorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siape', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Siape')),
                ('id_servidor_sig', models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID do servidor nos SIGs')),
                ('unidade_lotacao', models.CharField(max_length=200, verbose_name='Unidade de lotação')),
                ('unidade_exercicio', models.CharField(max_length=200, verbose_name='Unidade de exercício')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('tipo_servidor', models.CharField(max_length=200, verbose_name='Tipo de servidor')),
                ('categoria', models.CharField(max_length=200, verbose_name='Categoria')),
                ('regime_trabalho', models.CharField(max_length=100, verbose_name='Regime de trabalho')),
                ('situacao', models.CharField(max_length=200, verbose_name='Situação')),
                ('titulacao', models.CharField(max_length=200, verbose_name='Titulação')),
                ('is_ativo', models.BooleanField(default=True, help_text='Indica que o perfil será tratado como ativo. Ao invés de excluir perfis, desmarque isso.', verbose_name='Ativo?')),
            ],
        ),
        migrations.CreateModel(
            name='DocenteProfile',
            fields=[
                ('servidorprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.ServidorProfile')),
                ('lattes', models.URLField(verbose_name='Link do lattes')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
            bases=('authentication.servidorprofile',),
        ),
        migrations.CreateModel(
            name='TaeProfile',
            fields=[
                ('servidorprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.ServidorProfile')),
            ],
            options={
                'verbose_name': 'Técnico Administrativo',
                'verbose_name_plural': 'Técnicos Administrativos',
            },
            bases=('authentication.servidorprofile',),
        ),
        migrations.AddField(
            model_name='servidorprofile',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Pessoa'),
        ),
    ]
