# Generated by Django 2.1.7 on 2019-06-18 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20190618_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupodocente',
            name='grupo_pai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grupos_pai', to='authentication.GrupoDocente'),
        ),
    ]
