# Generated by Django 2.1.7 on 2019-07-31 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20190618_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidorprofile',
            name='unidade_exercicio',
            field=models.ForeignKey(default='INDEFINIDO', on_delete=django.db.models.deletion.PROTECT, related_name='unidade_exercicio_organizacional_fk', to='core.EstruturaOrganizacional'),
        ),
        migrations.AlterField(
            model_name='servidorprofile',
            name='unidade_lotacao',
            field=models.ForeignKey(default='INDEFINIDO', on_delete=django.db.models.deletion.PROTECT, related_name='unidade_lotacao_organizacional_fk', to='core.EstruturaOrganizacional'),
        ),
    ]
