# Generated by Django 2.1.7 on 2019-08-01 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20190731_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docenteprofile',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='docentes_grupo', to='authentication.GrupoDocente', verbose_name='Grupo em função da carga horária'),
        ),
        migrations.AlterField(
            model_name='docenteprofile',
            name='lattes',
            field=models.URLField(help_text='Ex: http://lattes.cnpq.br/2076449581151181', unique=True, verbose_name='Link do lattes'),
        ),
    ]
