# Generated by Django 2.1.7 on 2019-08-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20190801_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupodocente',
            name='ch_semanal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Carga horária semanal'),
        ),
    ]
