# Generated by Django 2.1.7 on 2019-08-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_grupodocente_ch_semanal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docenteprofile',
            name='lattes',
            field=models.URLField(blank=True, help_text='Ex: http://lattes.cnpq.br/2076449581151181', null=True, unique=True, verbose_name='Link do lattes'),
        ),
    ]
